[project]
name = "vector-hub"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mathieu", email = "mathieu.busse@ikmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "flask>=3.1.3",
    "flask-wtf>=1.2.2",
    "openai>=3.3.0",
    "pydantic>=2.13.4",
    "pymupdf>=1.28.2",
    "python-dotenv>=1.2.3",
    "tiktoken>=0.11.0",
]

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false
