from __future__ import annotations

from typing import Protocol

from models.document_model import ChunkModel, DocumentInfo, DocumentModel, PageModel


class DocumentRepository(Protocol):
    def list(self) -> list[DocumentInfo]: ...
    def get(self, document_id: str) -> DocumentModel: ...
    def save(self, document: DocumentModel) -> None: ...
    def delete(self, document_id: str) -> None: ...
    def replace_chunks(self, document_id: str, chunks: list[ChunkModel]) -> None: ...
    def update_chunk(self, chunk: ChunkModel, expected_version: int | None = None) -> None: ...
    def delete_chunk(self, document_id: str, chunk_id: str) -> bool: ...
    def insert_chunk(self, chunk: ChunkModel) -> None: ...
    def update_page(self, document_id: str, page: PageModel) -> None: ...
    def update_statuses(self, document_id: str, **statuses) -> None: ...


class VectorRepository(Protocol):
    def exists(self, chunk_id: str) -> bool: ...
    def save(self, chunk_id: str, model: str, input_hash: str, embedding: list[float]) -> None: ...
    def delete(self, chunk_id: str) -> None: ...
    def get_input_hash(self, chunk_id: str) -> str | None: ...
    def search(self, query_embedding: list[float], *, document_id: str | None = None,
               limit: int = 8) -> list[dict]: ...
